name: main workflow

# Controls when the action will run. 
on:
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs at 00:00 Europe/Lisbon everyday
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./_action
        with:
          args: ${{ secrets.GH_TOKEN }}
