name: README Updater

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs at 00:00 Europe/Lisbon everyday
  schedule:
    - cron: '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    name: Update Readme file
    runs-on: ubuntu-latest
    steps:
      - uses: DylanPerdigao/dylanperdigao@main
        with:
          args: ${{ secrets.GH_TOKEN }}
